export const CLIENT = {
  domain: "shield.rs",
  host: "https://www.shield.rs",
  name: "Shield",
  title: "Shield - An advanced IAM and CIAM solution",
  description:
    "Shield delivers a comprehensive solution for Identity and Access Management for modern applications. Built with the fastest and safest programming language to ensure unparalleled security and performance.",
  keywords: [
    "identity",
    "access",
    "management",
    "authentication",
    "authorization",
    "sso",
    "oauth",
    "openid",
    "saml",
    "jwt",
    "iam",
    "auth",
    "security",
    "shield",
    "shield.rs",
    "shield-rs",
    "shield-auth",
    "idp",
    "ciam",
    "identity-access-management",
    "identity-access-management-system",
    "openid-connect",
    "open source auth system",
  ],
};
